name: sekillendirisungaty
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  cached_network_image: any
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_iconly: ^1.0.2
  flutter_staggered_grid_view: ^0.4.0
  get: 4.6.5
  get_storage: 2.0.3
  dio:
  lottie: ^1.2.1
  path_provider: ^2.0.11
  permission_handler: 
  photo_view: ^0.13.0
  share: any
  url_launcher: 6.1.6
  vibration: ^1.7.5
  google_nav_bar: ^5.0.6
  flutter_cached_pdfview: ^0.4.1
  video_player: 
  carousel_slider: ^4.0.0
  flick_video_player: ^0.5.0
  firebase_core: ^1.23.0
  cloud_firestore: ^3.4.9
  firebase_storage: ^10.3.10
  firebase_core_platform_interface: 4.5.1
  image_gallery_saver: ^1.7.1
  pdfdownloader: 
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/fonts/
    - assets/lottie/
    - assets/icons/
    - assets/pdf/
    - assets/image/
  fonts:
    - family: GilroyBold
      fonts:
        - asset: assets/fonts/Gilroy-Bold.ttf
    - family: GilroyMedium
      fonts:
        - asset: assets/fonts/Gilroy-SemiBold.ttf
    - family: GilroyRegular
      fonts:
        - asset: assets/fonts/Gilroy-Medium.ttf
    - family: GilroyLight
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
  uses-material-design: true
  generate: true
